name: Deploy Application with Helm

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Extract the short 7-character Git commit ID
      - name: Get short Git commit ID
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Step 3: Authenticate with your EC2 Kubernetes Cluster
      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBERNETES_KUBE_CONFIG }}

      # Step 4: Install Helm CLI on the runner
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Update values in values.yaml
        run: |
          sed -i 's/IMAGEVERSION/"${{ steps.vars.outputs.sha_short }}"/g' ./charts/notes-app/values.yaml
          echo "=== Verification: Modified values.yaml ==="
          cat ./charts/notes-app/values.yaml

      # Step 6: Deploy by explicitly passing the modified values.yaml file
      - name: Deploy to Kubernetes via Helm
        run: |
          helm upgrade --install notes-app ./charts/notes-app \
            -f ./charts/notes-app/values.yaml \
            --timeout 15ms