name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ] # Triggers the build whenever you push to main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository code onto the runner
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Log into your Docker Hub account
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Step 2: Get the short 7-character commit ID
      - name: Get short Git commit ID
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Step 3: Build the Dockerfile and push it to your registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./notes-app
          file: ./notes-app/cd ..
          Dockerfile
          push: true
          # Replace 'my-app' with your preferred Docker Hub repository name
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:${{ steps.vars.outputs.sha_short }}